# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classification',
            name='slug',
            field=models.CharField(default='djangodbmodelsfieldscharfield', max_length=200),
        ),
    ]
