# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_classification_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='slug',
        ),
    ]
